name: helping_hand
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  cloud_firestore: ^4.12.2
  google_sign_in: ^6.1.5
  google_fonts: ^6.1.0
  country_state_city_pro: ^0.0.6
  uuid: ^3.0.7
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: lib/assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: lib/assets/fonts/Poppins/Poppins-Medium.ttf
  assets :
    - lib/assets/images/
