name: helping_hand
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  cloud_firestore: ^4.12.2
  google_sign_in: ^6.1.5
  google_fonts: ^6.1.0
  country_state_city_pro: ^0.0.6
  google_nav_bar: ^5.0.6
  provider: ^6.0.5
  uuid: ^4.2.1
  get: ^4.6.5
  firebase_messaging: ^14.7.4
  http: ^1.1.0
  flutter_notification_channel: ^2.0.0
  flutter_local_notifications: ^16.1.0
  loading_animation_widget: ^1.2.0+4
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  firebase_storage: ^11.5.1
  easy_upi_payment: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "lib/assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: lib/assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: lib/assets/fonts/Poppins/Poppins-Medium.ttf
  assets :
    - lib/assets/images/
    